add_rules("mode.debug", "mode.release")
local xmake_repo = path.join(path.directory(os.scriptdir()), "xmake-repo")
add_repositories("custom-xmake-repo " .. xmake_repo)
add_requires("mmg")
add_requires("glap")

target("test-mmg")
    add_rules("@mmg/mmg")
    set_kind("binary")
    set_languages("cxx20")
    add_files("src/main.cpp")
    add_files("args.glap.yml")
    add_packages("glap", "mmg")